# Generated by Django 5.2.5 on 2025-09-11 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_rename_organization_trainingpartner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='course',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_enrollments',
        ),
        
        # Add new fields
        migrations.AddField(
            model_name='course',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, help_text='Feedback from approvers'),
        ),
        migrations.AddField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('training_partner_pending', 'Pending Training Partner Approval'), ('super_pending', 'Pending Super Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/banners/', help_text='Course detail page banner image'),
        ),
        migrations.AddField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='courses/demos/', help_text='Course preview/demo video'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved_by_super_admin',
            field=models.BooleanField(default=False, help_text='Super admin has approved this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved_by_training_partner',
            field=models.BooleanField(default=False, help_text='Training partner admin has approved this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Course is still being created'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Course is live and visible to students'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_enrollment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(default='Students will learn various skills and concepts', help_text='What students will learn (bullet points or paragraph)'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='Course description', help_text='Brief description for course cards and previews', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='super_admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_approved_courses', to=settings.AUTH_USER_MODEL, help_text='Super admin who approved this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags for course discovery', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='training_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.trainingpartner', help_text='Training partner'),
        ),
        migrations.AddField(
            model_name='course',
            name='training_partner_admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_partner_approved_courses', to=settings.AUTH_USER_MODEL, help_text='Training partner admin who approved this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['tutor', 'admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, help_text='Tutor or Admin who created this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        
        # Update existing fields
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('frontend_development', 'Frontend Development'), ('backend_development', 'Backend Development'), ('data_analyst', 'Data Analyst'), ('data_science', 'Data Science'), ('interview_preparation', 'Interview Preparation'), ('ai_kids', 'AI for Kids'), ('programming_kids', 'Programming for Kids'), ('robotics', 'Robotics'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity')], default='frontend_development', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Course description', help_text='Full course description for course detail page'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4, help_text='Course duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Untitled Course', help_text='Course title as shown to students', max_length=200),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'level'], name='courses_cou_categor_e2e094_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['approval_status'], name='courses_cou_approva_5408e2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'is_featured'], name='courses_cou_is_publ_bc1413_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['training_partner'], name='courses_cou_trainin_744a67_idx'),
        ),
    ]
