# Generated by Django 5.2.5 on 2025-09-14 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='training_partner',
            field=models.ForeignKey(blank=True, help_text='Knowledge partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.knowledgepartner'),
        ),
        migrations.AddField(
            model_name='course',
            name='training_partner_admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Training partner admin who approved this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_partner_approved_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Tutor or Admin who created this course', limit_choices_to={'role__in': ['knowledge_partner_instructor', 'knowledge_partner_admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(help_text='Course this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursenotification',
            name='course',
            field=models.ForeignKey(help_text='Course related to the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursenotification',
            name='user',
            field=models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='course_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(help_text='Course this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursewishlist',
            name='course',
            field=models.ForeignKey(help_text='Course in wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursewishlist',
            name='student',
            field=models.ForeignKey(help_text='Student who added to wishlist', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Training partner admin who approved this enrollment', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='Course being enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_module',
            field=models.ForeignKey(blank=True, help_text='Current module being studied', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(help_text='Student enrolled in the course', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='enrollment',
            field=models.OneToOneField(help_text='Enrollment this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='enrollment',
            field=models.OneToOneField(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(help_text='Module this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, help_text='Current lesson being studied', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='lesson',
            field=models.ForeignKey(help_text='Lesson this material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='enrollment',
            field=models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(help_text='Lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'level'], name='courses_cou_categor_e2e094_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['approval_status'], name='courses_cou_approva_5408e2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'is_featured'], name='courses_cou_is_publ_bc1413_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['training_partner'], name='courses_cou_trainin_744a67_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_private', 'is_active'], name='courses_cou_is_priv_98993f_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'order'], name='courses_cou_course__dcfbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['is_published'], name='courses_cou_is_publ_5c949f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['user', 'is_read'], name='courses_cou_user_id_bb8b43_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['course'], name='courses_cou_course__ad4495_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['notification_type'], name='courses_cou_notific_547a05_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course', 'order'], name='courses_cou_course__55b494_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['resource_type'], name='courses_cou_resourc_936b51_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['student'], name='courses_cou_student_2707ea_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['course'], name='courses_cou_course__464c24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursewishlist',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['enrollment'], name='courses_cou_enrollm_a7cb52_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['rating'], name='courses_cou_rating_4bf87d_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['is_approved'], name='courses_cou_is_appr_924a69_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['enrollment'], name='courses_cou_enrollm_297e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['overall_progress'], name='courses_cou_overall_04dd32_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['last_activity'], name='courses_cou_last_ac_a6def2_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='courses_les_module__4accd4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='courses_les_lesson__299384_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published'], name='courses_les_is_publ_ebf633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='courses_enr_student_c86bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='courses_enr_course__78d524_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='courses_enr_enrollm_eb8905_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['progress_percentage'], name='courses_enr_progres_dba947_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_type'], name='courses_enr_enrollm_ecf17e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['approved_by'], name='courses_enr_approve_8f8cab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['lesson', 'order'], name='courses_les_lesson__ce6a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['material_type'], name='courses_les_materia_74a009_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='courses_les_enrollm_1a9f99_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='courses_les_lesson__770740_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['is_completed'], name='courses_les_is_comp_012467_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
    ]
