# Generated by Django 5.2.5 on 2025-09-11 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_update_course_model'),
        ('users', '0002_rename_organization_trainingpartner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create CourseModule model
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Module title', max_length=200)),
                ('description', models.TextField(help_text='Module description')),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=220)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of module in course')),
                ('duration_weeks', models.PositiveIntegerField(default=1, help_text='Module duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('is_published', models.BooleanField(default=True, help_text='Module is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['course', 'order'],
                'indexes': [models.Index(fields=['course', 'order'], name='courses_cou_course_2a3b4c_idx'), models.Index(fields=['is_published'], name='courses_cou_is_publ_5d6e7f_idx')],
            },
        ),
        
        # Create Lesson model
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Lesson description')),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=220)),
                ('lesson_type', models.CharField(choices=[('video', 'Video Lesson'), ('text', 'Text Lesson'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('live_session', 'Live Session'), ('download', 'Download')], default='video', help_text='Type of lesson', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lesson in module')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes')),
                ('is_preview', models.BooleanField(default=False, help_text='Lesson is available for preview')),
                ('is_published', models.BooleanField(default=True, help_text='Lesson is visible to students')),
                ('content', models.TextField(blank=True, help_text='Lesson content (for text lessons)')),
                ('video_url', models.URLField(blank=True, help_text='Video URL (for video lessons)')),
                ('video_file', models.FileField(blank=True, help_text='Video file (for video lessons)', null=True, upload_to='courses/lessons/videos/')),
                ('attachment', models.FileField(blank=True, help_text='Lesson attachment', null=True, upload_to='courses/lessons/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Module this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['module', 'order'],
                'indexes': [models.Index(fields=['module', 'order'], name='courses_les_module_8a9b0c_idx'), models.Index(fields=['lesson_type'], name='courses_les_lesson_1d2e3f_idx'), models.Index(fields=['is_published'], name='courses_les_is_publ_4g5h6i_idx')],
            },
        ),
        
        # Create LessonMaterial model
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Material title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Material description')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'PowerPoint Presentation'), ('zip', 'ZIP Archive'), ('image', 'Image'), ('audio', 'Audio File'), ('other', 'Other')], default='other', help_text='Type of material', max_length=20)),
                ('file', models.FileField(help_text='Material file', upload_to='courses/lessons/materials/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of downloads')),
                ('is_required', models.BooleanField(default=False, help_text='Material is required for the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='Lesson this material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Material',
                'verbose_name_plural': 'Lesson Materials',
                'ordering': ['lesson', 'title'],
                'indexes': [models.Index(fields=['lesson'], name='courses_les_lesson_7j8k9l_idx'), models.Index(fields=['material_type'], name='courses_les_materi_0m1n2o_idx')],
            },
        ),
        
        # Create CourseResource model
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Resource title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Resource description')),
                ('resource_type', models.CharField(choices=[('syllabus', 'Course Syllabus'), ('schedule', 'Course Schedule'), ('reference', 'Reference Material'), ('tool', 'Tool or Software'), ('link', 'External Link'), ('other', 'Other')], default='other', help_text='Type of resource', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Resource file', null=True, upload_to='courses/resources/')),
                ('url', models.URLField(blank=True, help_text='Resource URL (for external links)')),
                ('is_public', models.BooleanField(default=True, help_text='Resource is visible to all students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
                'ordering': ['course', 'title'],
                'indexes': [models.Index(fields=['course'], name='courses_cou_course_3p4q5r_idx'), models.Index(fields=['resource_type'], name='courses_cou_resour_6s7t8u_idx')],
            },
        ),
        
        # Create Enrollment model
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', help_text='Enrollment status', max_length=20)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of enrollment')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date of course completion', null=True)),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time student accessed the course', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Course completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for the course', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial', 'Partial')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course being enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('current_lesson', models.ForeignKey(blank=True, help_text='Current lesson being studied', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('current_module', models.ForeignKey(blank=True, help_text='Current module being studied', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemodule')),
                ('student', models.ForeignKey(help_text='Student enrolled in the course', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='courses_enu_student_9v0w1x_idx'), models.Index(fields=['course', 'status'], name='courses_enu_course_2y3z4a_idx'), models.Index(fields=['enrollment_date'], name='courses_enu_enroll_5b6c7d_idx'), models.Index(fields=['progress_percentage'], name='courses_enu_progre_8e9f0g_idx')],
            },
        ),
        
        # Create CourseReview model
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(default='Course Review', help_text='Review title', max_length=200)),
                ('content', models.TextField(default='Great course!', help_text='Review content')),
                ('is_approved', models.BooleanField(default=False, help_text='Review is approved and visible')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Review is anonymous')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(help_text='Enrollment this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment'], name='courses_cou_enroll_1h2i3j_idx'), models.Index(fields=['rating'], name='courses_cou_rating_4k5l6m_idx'), models.Index(fields=['is_approved'], name='courses_cou_is_app_7n8o9p_idx')],
            },
        ),
        
        # Create CourseWishlist model
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course in wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student who added to wishlist', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Wishlist',
                'verbose_name_plural': 'Course Wishlists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='courses_cou_student_0q1r2s_idx'), models.Index(fields=['course'], name='courses_cou_course_3t4u5v_idx')],
            },
        ),
        
        # Create CourseNotification model
        migrations.CreateModel(
            name='CourseNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Course Notification', help_text='Notification title', max_length=200)),
                ('message', models.TextField(default='You have a new course notification.', help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('completion', 'Completion'), ('new_lesson', 'New Lesson'), ('assignment_due', 'Assignment Due'), ('live_session', 'Live Session'), ('course_update', 'Course Update'), ('other', 'Other')], default='other', help_text='Type of notification', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Notification has been read')),
                ('is_email_sent', models.BooleanField(default=False, help_text='Email notification has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(help_text='Course related to the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.course')),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='course_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Notification',
                'verbose_name_plural': 'Course Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='courses_cou_user_i_6w7x8y_idx'), models.Index(fields=['course'], name='courses_cou_course_9z0a1b_idx'), models.Index(fields=['notification_type'], name='courses_cou_notifi_2c3d4e_idx')],
            },
        ),
        
        # Create LessonProgress model
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='Lesson is completed')),
                ('is_started', models.BooleanField(default=False, help_text='Lesson has been started')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Lesson completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Time spent on lesson in minutes')),
                ('started_at', models.DateTimeField(blank=True, help_text='When lesson was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When lesson was completed', null=True)),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time lesson was accessed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(help_text='Lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'ordering': ['enrollment', 'lesson__order'],
                'indexes': [models.Index(fields=['enrollment', 'is_completed'], name='courses_les_enroll_5f6g7h_idx'), models.Index(fields=['lesson'], name='courses_les_lesson_8i9j0k_idx'), models.Index(fields=['is_completed'], name='courses_les_is_com_1l2m3n_idx')],
            },
        ),
        
        # Create ModuleProgress model
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='Module is completed')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Module completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lessons_completed', models.PositiveIntegerField(default=0, help_text='Number of lessons completed in module')),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Total number of lessons in module')),
                ('started_at', models.DateTimeField(blank=True, help_text='When module was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When module was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.enrollment')),
                ('module', models.ForeignKey(help_text='Module being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progress',
                'ordering': ['enrollment', 'module__order'],
                'indexes': [models.Index(fields=['enrollment', 'is_completed'], name='courses_mod_enroll_4o5p6q_idx'), models.Index(fields=['module'], name='courses_mod_module_7r8s9t_idx'), models.Index(fields=['is_completed'], name='courses_mod_is_com_0u1v2w_idx')],
            },
        ),
        
        # Create CourseProgress model
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall course progress percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modules_completed', models.PositiveIntegerField(default=0, help_text='Number of modules completed')),
                ('total_modules', models.PositiveIntegerField(default=0, help_text='Total number of modules in course')),
                ('lessons_completed', models.PositiveIntegerField(default=0, help_text='Number of lessons completed')),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Total number of lessons in course')),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent on course in minutes')),
                ('average_session_duration_minutes', models.PositiveIntegerField(default=0, help_text='Average session duration in minutes')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When course was started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When course was completed', null=True)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last activity on course', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['enrollment'], name='courses_cou_enroll_3x4y5z_idx'), models.Index(fields=['overall_progress'], name='courses_cou_overal_6a7b8c_idx'), models.Index(fields=['last_activity'], name='courses_cou_last_a_9d0e1f_idx')],
            },
        ),
        
        # Create StudySession model
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_duration_minutes', models.PositiveIntegerField(default=0, help_text='Session duration in minutes')),
                ('progress_made', models.DecimalField(decimal_places=2, default=0.0, help_text='Progress made during this session', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When session started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.enrollment')),
                ('lesson', models.ForeignKey(blank=True, help_text='Lesson being studied (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['enrollment'], name='courses_stu_enroll_2g3h4i_idx'), models.Index(fields=['lesson'], name='courses_stu_lesson_5j6k7l_idx'), models.Index(fields=['started_at'], name='courses_stu_starte_8m9n0o_idx')],
            },
        ),
        
        # Add unique constraints
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='courses_coursemodule_unique_course_order'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='courses_lesson_unique_module_order'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='courses_enrollment_unique_student_course'),
        ),
        migrations.AddConstraint(
            model_name='coursewishlist',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='courses_coursewishlist_unique_student_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='courses_lessonprogress_unique_enrollment_lesson'),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'module'), name='courses_moduleprogress_unique_enrollment_module'),
        ),
    ]
