# Generated by Django 5.2.5 on 2025-09-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0006_kpinstructorprofile_kpprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='training_partner',
            field=models.ForeignKey(blank=True, help_text='Knowledge partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.kpprofile'),
        ),
    ]
