# Generated by Django 5.2.5 on 2025-09-11 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_new_models'),
        ('users', '0002_rename_organization_trainingpartner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create LessonMaterial model
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Material title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Material description')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'PowerPoint Presentation'), ('zip', 'ZIP Archive'), ('image', 'Image'), ('audio', 'Audio File'), ('other', 'Other')], default='other', help_text='Type of material', max_length=20)),
                ('file', models.FileField(help_text='Material file', upload_to='courses/lessons/materials/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of downloads')),
                ('is_required', models.BooleanField(default=False, help_text='Material is required for the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='Lesson this material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Material',
                'verbose_name_plural': 'Lesson Materials',
                'ordering': ['lesson', 'title'],
            },
        ),
        
        # Create CourseResource model
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Resource title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Resource description')),
                ('resource_type', models.CharField(choices=[('syllabus', 'Course Syllabus'), ('schedule', 'Course Schedule'), ('reference', 'Reference Material'), ('tool', 'Tool or Software'), ('link', 'External Link'), ('other', 'Other')], default='other', help_text='Type of resource', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Resource file', null=True, upload_to='courses/resources/')),
                ('url', models.URLField(blank=True, help_text='Resource URL (for external links)')),
                ('is_public', models.BooleanField(default=True, help_text='Resource is visible to all students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
                'ordering': ['course', 'title'],
            },
        ),
        
        # Create CourseWishlist model
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course in wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student who added to wishlist', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Wishlist',
                'verbose_name_plural': 'Course Wishlists',
                'ordering': ['-created_at'],
            },
        ),
        
        # Create CourseNotification model
        migrations.CreateModel(
            name='CourseNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Course Notification', help_text='Notification title', max_length=200)),
                ('message', models.TextField(default='You have a new course notification.', help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('completion', 'Completion'), ('new_lesson', 'New Lesson'), ('assignment_due', 'Assignment Due'), ('live_session', 'Live Session'), ('course_update', 'Course Update'), ('other', 'Other')], default='other', help_text='Type of notification', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Notification has been read')),
                ('is_email_sent', models.BooleanField(default=False, help_text='Email notification has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(help_text='Course related to the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.course')),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='course_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Notification',
                'verbose_name_plural': 'Course Notifications',
                'ordering': ['-created_at'],
            },
        ),
        
        # Create LessonProgress model
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='Lesson is completed')),
                ('is_started', models.BooleanField(default=False, help_text='Lesson has been started')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Lesson completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Time spent on lesson in minutes')),
                ('started_at', models.DateTimeField(blank=True, help_text='When lesson was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When lesson was completed', null=True)),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time lesson was accessed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(help_text='Lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'ordering': ['enrollment', 'lesson__order'],
            },
        ),
        
        # Create ModuleProgress model
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='Module is completed')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Module completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lessons_completed', models.PositiveIntegerField(default=0, help_text='Number of lessons completed in module')),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Total number of lessons in module')),
                ('started_at', models.DateTimeField(blank=True, help_text='When module was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When module was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.coursemodule')),
                ('module', models.ForeignKey(help_text='Module being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progress',
                'ordering': ['enrollment', 'module__order'],
            },
        ),
        
        # Create CourseProgress model
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall course progress percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modules_completed', models.PositiveIntegerField(default=0, help_text='Number of modules completed')),
                ('total_modules', models.PositiveIntegerField(default=0, help_text='Total number of modules in course')),
                ('lessons_completed', models.PositiveIntegerField(default=0, help_text='Number of lessons completed')),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Total number of lessons in course')),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent on course in minutes')),
                ('average_session_duration_minutes', models.PositiveIntegerField(default=0, help_text='Average session duration in minutes')),
                ('started_at', models.DateTimeField(default=timezone.now, help_text='When course was started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When course was completed', null=True)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last activity on course', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress',
                'ordering': ['-last_activity'],
            },
        ),
        
        # Create StudySession model
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_duration_minutes', models.PositiveIntegerField(default=0, help_text='Session duration in minutes')),
                ('progress_made', models.DecimalField(decimal_places=2, default=0.0, help_text='Progress made during this session', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(default=timezone.now, help_text='When session started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.enrollment')),
                ('lesson', models.ForeignKey(blank=True, help_text='Lesson being studied (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
