# Generated by Django 5.2.5 on 2025-09-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_missing_models'),
    ]

    operations = [
    ]
