# Generated by Django 5.2.5 on 2025-09-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_training_partner_admin_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursemodule',
            name='courses_cou_is_publ_5c949f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='courses_les_is_publ_ebf633_idx',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
    ]
