# Generated by Django 5.2.5 on 2025-09-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_coursemodule_courses_cou_is_publ_5c949f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old indexes
        migrations.RemoveIndex(
            model_name='coursewishlist',
            name='courses_cou_student_2707ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='courses_enr_student_c86bf5_idx',
        ),
        
        # Step 2: Add new fields first
        migrations.AddField(
            model_name='coursewishlist',
            name='learner',
            field=models.ForeignKey(blank=True, help_text='Learner who added to wishlist', limit_choices_to={'role': 'learner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='learner',
            field=models.ForeignKey(default='5c33e835-3203-4793-81b2-5d1b1f622665', help_text='Learner enrolled in the course', limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        
        # Step 3: Update unique constraints after fields are added
        migrations.AlterUniqueTogether(
            name='coursewishlist',
            unique_together={('learner', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('learner', 'course')},
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Resource is visible to all learners'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('admin_created', 'Created by Admin'), ('learner_requested', 'Requested by Learner')], default='learner_requested', help_text='How this enrollment was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time learner accessed the course', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date when learner started learning (after approval)', null=True),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['learner'], name='courses_cou_learner_114481_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['learner', 'status'], name='courses_enr_learner_032779_idx'),
        ),
        migrations.RemoveField(
            model_name='coursewishlist',
            name='student',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
    ]
