# Generated by Django 5.2.5 on 2025-09-12 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_final_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursemodule',
            name='courses_coursemodule_unique_course_order',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='courses_enrollment_unique_student_course',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='courses_lesson_unique_module_order',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_categor_fec4a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_level_bf0a39_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_status_158bbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_organiz_e21838_idx',
        ),
        migrations.RenameIndex(
            model_name='coursemodule',
            new_name='courses_cou_course__dcfbc2_idx',
            old_name='courses_cou_course_2a3b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='coursemodule',
            new_name='courses_cou_is_publ_5c949f_idx',
            old_name='courses_cou_is_publ_5d6e7f_idx',
        ),
        migrations.RenameIndex(
            model_name='coursereview',
            new_name='courses_cou_enrollm_a7cb52_idx',
            old_name='courses_cou_enroll_1h2i3j_idx',
        ),
        migrations.RenameIndex(
            model_name='coursereview',
            new_name='courses_cou_rating_4bf87d_idx',
            old_name='courses_cou_rating_4k5l6m_idx',
        ),
        migrations.RenameIndex(
            model_name='coursereview',
            new_name='courses_cou_is_appr_924a69_idx',
            old_name='courses_cou_is_app_7n8o9p_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='courses_enr_student_c86bf5_idx',
            old_name='courses_enu_student_9v0w1x_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='courses_enr_course__78d524_idx',
            old_name='courses_enu_course_2y3z4a_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='courses_enr_enrollm_eb8905_idx',
            old_name='courses_enu_enroll_5b6c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='courses_enr_progres_dba947_idx',
            old_name='courses_enu_progre_8e9f0g_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='courses_les_module__4accd4_idx',
            old_name='courses_les_module_8a9b0c_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='courses_les_lesson__299384_idx',
            old_name='courses_les_lesson_1d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='courses_les_is_publ_ebf633_idx',
            old_name='courses_les_is_publ_4g5h6i_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured courses section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='What students should know before taking this course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of title', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Course card thumbnail image', null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='enrollment',
            field=models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursewishlist',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('enrollment', 'module')},
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['user', 'is_read'], name='courses_cou_user_id_bb8b43_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['course'], name='courses_cou_course__ad4495_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['notification_type'], name='courses_cou_notific_547a05_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['enrollment'], name='courses_cou_enrollm_297e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['overall_progress'], name='courses_cou_overall_04dd32_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['last_activity'], name='courses_cou_last_ac_a6def2_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course'], name='courses_cou_course__9b360b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['resource_type'], name='courses_cou_resourc_936b51_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['student'], name='courses_cou_student_2707ea_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['course'], name='courses_cou_course__464c24_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['lesson'], name='courses_les_lesson__ed193b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['material_type'], name='courses_les_materia_74a009_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='courses_les_enrollm_1a9f99_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='courses_les_lesson__770740_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['is_completed'], name='courses_les_is_comp_012467_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='courses_mod_enrollm_1942a5_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['module'], name='courses_mod_module__1fb606_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['is_completed'], name='courses_mod_is_comp_24039d_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['enrollment'], name='courses_stu_enrollm_20d186_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['lesson'], name='courses_stu_lesson__46728c_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['started_at'], name='courses_stu_started_3c95c9_idx'),
        ),
    ]
