# Generated by Django 5.2.5 on 2025-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_learner_field_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Course is live and visible to learners'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(default='Learners will learn various skills and concepts', help_text='What learners will learn (bullet points or paragraph)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='What learners should know before taking this course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Untitled Course', help_text='Course title as shown to learners', max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='is_downloadable',
            field=models.BooleanField(default=True, help_text='Learners can download this material'),
        ),
    ]
