# Generated by Django 5.2.5 on 2025-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_coursemodule_courses_coursemodule_unique_course_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='slug',
            field=models.SlugField(max_length=220, help_text='URL-friendly version of title', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=220, help_text='URL-friendly version of title', default=''),
            preserve_default=False,
        ),
    ]
