# Generated by Django 5.2.5 on 2025-09-20 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_completion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='The date of the session')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', help_text='Attendance status for the session', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the attendance', null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='When the attendance was marked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='The course for which attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.course')),
                ('learner', models.ForeignKey(help_text='The learner whose attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(help_text='The instructor who marked the attendance', on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-session_date', 'learner__full_name'],
                'unique_together': {('learner', 'course', 'session_date')},
            },
        ),
    ]
