# Generated by Django 5.2.5 on 2025-10-04 17:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_attendance_model'),
        ('users', '0024_otpverification_temp_user_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Session title visible to learners', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what will be covered in this session')),
                ('scheduled_datetime', models.DateTimeField(help_text='When the session is scheduled to start')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Session duration in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('meeting_link', models.URLField(help_text='Direct link to join the live session', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('meeting_platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('microsoft_teams', 'Microsoft Teams'), ('other', 'Other Platform')], default='zoom', help_text='Platform being used for the session', max_length=50)),
                ('meeting_id', models.CharField(blank=True, help_text='Meeting ID or room number (optional)', max_length=200, null=True)),
                ('meeting_password', models.CharField(blank=True, help_text='Meeting password if required (optional)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Super Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('live', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the session', max_length=30)),
                ('is_approved', models.BooleanField(default=False, help_text='Super admin has approved this session')),
                ('approval_notes', models.TextField(blank=True, help_text='Feedback from super admin', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the session was approved', null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (optional)', null=True)),
                ('is_recording_enabled', models.BooleanField(default=True, help_text='Whether this session will be recorded')),
                ('recording_link', models.URLField(blank=True, help_text='Link to session recording (added after session)', max_length=500, null=True)),
                ('session_notes', models.TextField(blank=True, help_text='Pre-session notes or agenda from instructor', null=True)),
                ('post_session_notes', models.TextField(blank=True, help_text='Summary or notes added after session completion', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether enrollment notification emails have been sent')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder emails have been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Super admin who approved this session', limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sessions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('instructor', models.ForeignKey(help_text='Instructor hosting this session', limit_choices_to={'role': 'knowledge_partner_instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('training_partner', models.ForeignKey(help_text='Knowledge Partner organization this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='users.kpprofile')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-scheduled_datetime'],
                'indexes': [models.Index(fields=['course', 'scheduled_datetime'], name='courses_liv_course__8e09dc_idx'), models.Index(fields=['instructor', 'status'], name='courses_liv_instruc_1d515f_idx'), models.Index(fields=['status', 'scheduled_datetime'], name='courses_liv_status_cbde36_idx'), models.Index(fields=['training_partner', 'status'], name='courses_liv_trainin_246d01_idx')],
            },
        ),
    ]
