# Generated by Django 5.2.5 on 2025-09-12 04:04

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_slug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=1, help_text='Module duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Lesson is available for preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL (for video lessons)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Lesson content (for text lessons)'),
            preserve_default=False,
        ),
    ]
