# Generated by Django 5.2.5 on 2025-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_livesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, help_text='PDF or document file upload', null=True, upload_to='courses/lessons/documents/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Image file upload', null=True, upload_to='courses/lessons/images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('pdf', 'PDF Document'), ('document', 'Document'), ('text', 'Text Lesson'), ('image', 'Image'), ('assignment', 'Assignment'), ('image_gallery', 'Image Gallery'), ('mixed', 'Mixed Content')], default='video', help_text='Type of lesson', max_length=20),
        ),
    ]
