# Generated by Django 5.2.5 on 2025-09-13 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_fix_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=1, help_text='Module duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Lesson is available for preview'),
        ),
    ]
