# Generated by Django 5.2.5 on 2025-09-13 08:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_add_enrollment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=1, help_text='Module duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Payment Initiated'), ('paid', 'Payment Successful'), ('failed', 'Payment Failed'), ('verified', 'Admin Verified'), ('rejected', 'Admin Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courses.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='courses.payment')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('user', 'Student'), ('admin', 'Training Partner Admin'), ('super_admin', 'Super Admin')], max_length=20)),
                ('notification_type', models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('verification_needed', 'Admin Verification Needed'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('enrollment_activated', 'Enrollment Activated')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('course_title', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.payment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Notification',
                'verbose_name_plural': 'Payment Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=500, null=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='courses.payment')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='courses_pay_status_da6f59_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='courses_pay_razorpa_d82651_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['webhook_received'], name='courses_pay_webhook_b969e6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='courses_pay_recipie_b9677c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['notification_type'], name='courses_pay_notific_ebedb3_idx'),
        ),
    ]
