# Generated by Django 5.2.5 on 2025-09-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_coursemodule_duration_weeks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='PaymentWebhook',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
        migrations.DeleteModel(
            name='PaymentNotification',
        ),
    ]
