# Generated by Django 5.2.5 on 2025-09-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_payment_enrollment_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment RENAME COLUMN enrolled_at TO enrollment_date;",
            reverse_sql="ALTER TABLE courses_enrollment RENAME COLUMN enrollment_date TO enrolled_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment RENAME COLUMN completed_at TO completion_date;",
            reverse_sql="ALTER TABLE courses_enrollment RENAME COLUMN completion_date TO completed_at;"
        ),
    ]
