# Generated by Django 5.2.5 on 2025-09-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_rename_enrolled_at_to_enrollment_date'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment ADD COLUMN IF NOT EXISTS current_module_id UUID REFERENCES courses_coursemodule(id);",
            reverse_sql="ALTER TABLE courses_enrollment DROP COLUMN IF EXISTS current_module_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment ADD COLUMN IF NOT EXISTS current_lesson_id UUID REFERENCES courses_lesson(id);",
            reverse_sql="ALTER TABLE courses_enrollment DROP COLUMN IF EXISTS current_lesson_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) DEFAULT 'pending';",
            reverse_sql="ALTER TABLE courses_enrollment DROP COLUMN IF EXISTS payment_status;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(100) DEFAULT '';",
            reverse_sql="ALTER TABLE courses_enrollment DROP COLUMN IF EXISTS payment_reference;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();",
            reverse_sql="ALTER TABLE courses_enrollment DROP COLUMN IF EXISTS created_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE courses_enrollment ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();",
            reverse_sql="ALTER TABLE courses_enrollment DROP COLUMN IF EXISTS updated_at;"
        ),
    ]
