# Generated by Django 5.2.5 on 2025-09-14 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_add_missing_enrollment_fields'),
        ('users', '0002_rename_organization_trainingpartner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleprogress',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='moduleprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='lesson',
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['course', 'order', 'title'], 'verbose_name': 'Course Resource', 'verbose_name_plural': 'Course Resources'},
        ),
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={'ordering': ['lesson', 'order', 'title'], 'verbose_name': 'Lesson Material', 'verbose_name_plural': 'Lesson Materials'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['enrollment', 'lesson__module__order', 'lesson__order'], 'verbose_name': 'Lesson Progress', 'verbose_name_plural': 'Lesson Progress'},
        ),
        migrations.RemoveIndex(
            model_name='courseresource',
            name='courses_cou_course__9b360b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonmaterial',
            name='courses_les_lesson__ed193b_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_approved_by_super_admin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='super_admin_approved_by',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='average_session_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='modules_completed',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='total_modules',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='total_time_spent_minutes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='time_spent_minutes',
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Course is currently active and available for enrollments (inactive = ended/paused)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Private courses are only visible to learners from the same organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_enrollments',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of enrollments allowed (leave blank for unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_admin_enrollment',
            field=models.BooleanField(default=True, help_text='All enrollments require training partner admin approval'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of resource'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about this enrollment', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date when enrollment was approved', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Training partner admin who approved this enrollment', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('admin_created', 'Created by Admin'), ('student_requested', 'Requested by Student')], default='student_requested', help_text='How this enrollment was created', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date when student started learning (after approval)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Lesson must be completed to progress'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='is_downloadable',
            field=models.BooleanField(default=True, help_text='Students can download this material'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of material in lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Feedback from training partner admin', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Training Partner Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('frontend_development', 'Frontend Development'), ('backend_development', 'Backend Development'), ('programming_languages', 'Programming Languages'), ('ai', 'Artificial Intelligence'), ('ai_tools', 'AI Tools'), ('data_science', 'Data Science'), ('data_analysis', 'Data Analysis'), ('software_engineering', 'Software Engineering Essentials')], default='frontend_development', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title',
            field=models.CharField(help_text='Module/Topic title', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursenotification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('completion', 'Completion'), ('new_lesson', 'New Lesson'), ('assignment_due', 'Assignment Due'), ('live_session', 'Live Session'), ('course_update', 'Course Update'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('other', 'Other')], default='other', help_text='Type of notification', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='resource_type',
            field=models.CharField(choices=[('syllabus', 'Course Syllabus'), ('schedule', 'Course Schedule'), ('reference', 'Reference Material'), ('tool', 'Tool or Software'), ('link', 'External Link'), ('certificate_template', 'Certificate Template'), ('other', 'Other')], default='other', help_text='Type of resource', max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when enrollment was requested/created'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='pending_approval', help_text='Enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Lesson content (rich text for text lessons, assignment instructions, etc.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes (auto-detected from video files)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('text', 'Text Lesson'), ('assignment', 'Assignment'), ('image_gallery', 'Image Gallery'), ('mixed', 'Mixed Content')], default='video', help_text='Type of lesson', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Lesson/Subtopic title', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video file upload (duration will be auto-detected)', null=True, upload_to='courses/lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'PowerPoint Presentation'), ('zip', 'ZIP Archive'), ('image', 'Image'), ('video', 'Video File'), ('code', 'Code File'), ('other', 'Other')], default='other', help_text='Type of material', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_private', 'is_active'], name='courses_cou_is_priv_98993f_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course', 'order'], name='courses_cou_course__55b494_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_type'], name='courses_enr_enrollm_ecf17e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['approved_by'], name='courses_enr_approve_8f8cab_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['lesson', 'order'], name='courses_les_lesson__ce6a8b_idx'),
        ),
        migrations.DeleteModel(
            name='ModuleProgress',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
