# Generated by Django 5.2.5 on 2025-09-14 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_moduleprogress_unique_together_and_more'),
        ('users', '0004_remove_trainingpartner_employee_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='training_partner',
            field=models.ForeignKey(blank=True, help_text='Knowledge partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.trainingpartner'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Tutor or Admin who created this course', limit_choices_to={'role__in': ['knowledge_partner_instructor', 'knowledge_partner_admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
