# Generated by Django 5.2.5 on 2025-09-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'knowledge_partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'Learner'), ('admin', 'Knowledge Partner Admin'), ('super_admin', 'Super Admin')], max_length=20),
        ),
    ]
