# Generated by Django 5.2.5 on 2025-09-15 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpaprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='kpaprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='kpaprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='kpaprofile',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='kpiprofile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='knowledgepartner',
            name='type',
            field=models.CharField(choices=[('company', 'Company'), ('organization', 'Organization'), ('university', 'University'), ('institute', 'Institute'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='KnowledgePartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(help_text='Name of the organization applying', max_length=200)),
                ('organization_type', models.CharField(choices=[('company', 'Company'), ('organization', 'Organization'), ('university', 'University'), ('institute', 'Institute'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], help_text='Type of organization', max_length=50)),
                ('website_url', models.URLField(help_text="Organization's official website")),
                ('organization_email', models.EmailField(help_text='Official organization email', max_length=254)),
                ('contact_number', models.CharField(help_text='Phone number for callback', max_length=20)),
                ('courses_interested_in', models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('programming', 'Programming & Development'), ('data_science', 'Data Science & Analytics'), ('cybersecurity', 'Cybersecurity'), ('cloud_computing', 'Cloud Computing'), ('digital_marketing', 'Digital Marketing'), ('soft_skills', 'Soft Skills'), ('other', 'Other')], help_text='Primary course category they want to offer', max_length=50)),
                ('experience_years', models.CharField(choices=[('0-1', '0-1 years'), ('2-5', '2-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], help_text='Years of experience in education/training', max_length=10)),
                ('expected_tutors', models.CharField(choices=[('1-2', '1-2 tutors'), ('3-5', '3-5 tutors'), ('6-10', '6-10 tutors'), ('10+', '10+ tutors')], help_text='Expected number of tutors', max_length=10)),
                ('partner_message', models.TextField(blank=True, help_text='Additional message from the applicant', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin review/phone call', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_knowledge_partner', models.ForeignKey(blank=True, help_text='Knowledge Partner created from this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='users.knowledgepartner')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Partner Application',
                'verbose_name_plural': 'Knowledge Partner Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_knowl_status_a88f3a_idx'), models.Index(fields=['organization_email'], name='users_knowl_organiz_07f0f8_idx'), models.Index(fields=['contact_number'], name='users_knowl_contact_9bbaf0_idx')],
            },
        ),
    ]
