# Generated by Django 5.2.5 on 2025-09-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='TrainingPartner',
        ),
        migrations.AlterModelOptions(
            name='trainingpartner',
            options={'ordering': ['name'], 'verbose_name': 'Training Partner', 'verbose_name_plural': 'Training Partners'},
        ),
    ]
