# Generated by Django 5.2.5 on 2025-09-15 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_remove_kpaprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='knowledgepartnerapplication',
            name='users_knowl_status_a88f3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepartnerapplication',
            name='users_knowl_organiz_07f0f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepartnerapplication',
            name='users_knowl_contact_9bbaf0_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_99252e_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_organiz_1faf3a_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='knowledgepartnerapplication',
            name='created_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='added_by_admin',
            field=models.ForeignKey(blank=True, help_text='KP Admin who added this learner to the organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_learners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_added_by_kp_admin',
            field=models.BooleanField(default=False, help_text='True if this learner was added to knowledge partner by KP Admin (gives private course access)'),
        ),
        migrations.AddField(
            model_name='user',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, help_text='Knowledge partner organization - gives access to private courses. Only KP Admin can add learners to their organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.knowledgepartner'),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='courses_interested_in',
            field=models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('programming', 'Programming & Development'), ('data_science', 'Data Science & Analytics'), ('cybersecurity', 'Cybersecurity'), ('cloud_computing', 'Cloud Computing'), ('digital_marketing', 'Digital Marketing'), ('soft_skills', 'Soft Skills'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='created_knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.knowledgepartner'),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='expected_tutors',
            field=models.CharField(choices=[('1-2', '1-2 tutors'), ('3-5', '3-5 tutors'), ('6-10', '6-10 tutors'), ('10+', '10+ tutors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='experience_years',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('2-5', '2-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='organization_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='organization_type',
            field=models.CharField(choices=[('company', 'Company'), ('organization', 'Organization'), ('university', 'University'), ('institute', 'Institute'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='partner_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='website_url',
            field=models.URLField(),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'knowledge_partner'], name='users_user_role_7480ed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['knowledge_partner', 'is_approved'], name='users_user_knowled_efbf19_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_added_by_kp_admin'], name='users_user_is_adde_da587a_idx'),
        ),
    ]
