# Generated by Django 5.2.5 on 2025-09-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_rename_organization_trainingpartner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='employee_count',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], help_text='Number of employees', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year organization was established', null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Organization has been verified by admin'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn company page URL', null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='training_partners/logos/'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingpartner',
            name='type',
            field=models.CharField(choices=[('company', 'Company'), ('organization', 'Organization'), ('university', 'University'), ('institute', 'Institute'), ('bootcamp', 'Bootcamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Training partner organization (optional for students, required for tutors/admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.trainingpartner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('kpi', 'Knowlege Patner Instructor'), ('kpa', 'Knowlege Patner Admin')], default='learner', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trainingpartner',
            index=models.Index(fields=['is_active', 'is_verified'], name='users_train_is_acti_1cf5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingpartner',
            index=models.Index(fields=['type'], name='users_train_type_fd2fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'organization'], name='users_user_role_99252e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'is_approved'], name='users_user_organiz_1faf3a_idx'),
        ),
    ]
