# Generated by Django 5.2.5 on 2025-09-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_bio_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_approve_tutors',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_manage_courses',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_view_analytics',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_learning_style',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='preferred_student_level',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='teaching_style',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='timezone',
        ),
    ]
