# Generated by Django 5.2.5 on 2025-09-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='created_knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='users.knowledgepartner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('knowledge_partner_instructor', 'Knowledge Partner Instructor'), ('knowledge_partner_admin', 'Knowledge Partner Admin'), ('super_admin', 'Super Admin')], default='learner', max_length=30),
        ),
        migrations.AddIndex(
            model_name='knowledgepartnerapplication',
            index=models.Index(fields=['status', 'created_at'], name='users_knowl_status_a88f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepartnerapplication',
            index=models.Index(fields=['organization_email'], name='users_knowl_organiz_07f0f8_idx'),
        ),
    ]
