# Generated by Django 5.2.5 on 2025-09-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trainingpartner_email_trainingpartner_employee_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpartner',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='trainingpartner',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='trainingpartner',
            name='registration_number',
        ),
    ]
