# Generated by Django 5.2.5 on 2025-09-14 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_rename_models_and_roles'),
        ('users', '0004_remove_trainingpartner_employee_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(help_text='Professional bio for students to see')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/tutors/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(help_text='e.g., Senior Software Engineer, Data Scientist', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highest_education', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Certification'), ('self_taught', 'Self-Taught')], max_length=50)),
                ('certifications', models.TextField(blank=True, help_text='List your professional certifications', null=True)),
                ('specializations', models.TextField(help_text='Areas of expertise (comma-separated)')),
                ('technologies', models.TextField(help_text='Technologies you can teach (comma-separated)')),
                ('languages_spoken', models.TextField(default='English', help_text='Languages you can teach in')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profiles',
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/students/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=50, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('current_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('learning_goals', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learner Profile',
                'verbose_name_plural': 'Learner Profiles',
            },
        ),
        migrations.RenameModel(
            old_name='TrainingPartner',
            new_name='KnowledgePartner',
        ),
        migrations.RenameModel(
            old_name='AdminProfile',
            new_name='KPAProfile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='knowledgepartner',
            options={'ordering': ['name'], 'verbose_name': 'Knowledge Partner', 'verbose_name_plural': 'Knowledge Partners'},
        ),
        migrations.RenameIndex(
            model_name='knowledgepartner',
            new_name='users_knowl_is_acti_3998b6_idx',
            old_name='users_train_is_acti_1cf5a1_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgepartner',
            new_name='users_knowl_type_85d045_idx',
            old_name='users_train_type_fd2fd0_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Knowledge partner organization (optional for learners, required for instructors/admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.knowledgepartner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('knowledge_partner_instructor', 'Knowledge Partner Instructor'), ('knowledge_partner_admin', 'Knowledge Partner Admin')], default='learner', max_length=30),
        ),
        migrations.AddField(
            model_name='kpiprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
