# Generated by Django 5.2.5 on 2025-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_knowledgepartnerapplication_created_knowledge_partner_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgepartnerapplication',
            name='users_knowl_organiz_07f0f8_idx',
        ),
        migrations.RenameField(
            model_name='knowledgepartnerapplication',
            old_name='organization_email',
            new_name='knowledge_partner_email',
        ),
        migrations.RenameField(
            model_name='knowledgepartnerapplication',
            old_name='organization_name',
            new_name='knowledge_partner_name',
        ),
        migrations.RenameField(
            model_name='knowledgepartnerapplication',
            old_name='organization_type',
            new_name='knowledge_partner_type',
        ),
        migrations.AddIndex(
            model_name='knowledgepartnerapplication',
            index=models.Index(fields=['knowledge_partner_email'], name='users_knowl_knowled_06a0db_idx'),
        ),
    ]
