# Generated by Django 5.2.5 on 2025-09-15 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_knowledgepartnerapplication_users_knowl_organiz_07f0f8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPInstructorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(help_text='Professional bio for learners to see')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/instructors/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(help_text='e.g., Senior Software Engineer, Data Scientist', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highest_education', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Certification'), ('self_taught', 'Self-Taught')], max_length=50)),
                ('certifications', models.TextField(blank=True, help_text='List your professional certifications', null=True)),
                ('specializations', models.TextField(help_text='Areas of expertise (comma-separated)')),
                ('technologies', models.TextField(help_text='Technologies you can teach (comma-separated)')),
                ('languages_spoken', models.TextField(default='English', help_text='Languages you can teach in')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profiles',
            },
        ),
        migrations.CreateModel(
            name='KPProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=200, unique=True)),
                ('type', models.CharField(choices=[('company', 'Company'), ('organization', 'Organization'), ('university', 'University'), ('institute', 'Institute'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='About the organization')),
                ('location', models.CharField(help_text='Organization address/location', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Organization website', null=True)),
                ('kp_admin_name', models.CharField(help_text='Admin contact name', max_length=200)),
                ('kp_admin_email', models.EmailField(help_text='Admin personal email', max_length=254)),
                ('kp_admin_phone', models.CharField(blank=True, help_text='Admin phone number', max_length=15, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='knowledge_partners/logos/')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn company page URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Organization is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Organization has been verified by super admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Partner Profile',
                'verbose_name_plural': 'Knowledge Partner Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='knowledge_partner',
        ),
        migrations.RemoveField(
            model_name='kpaprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kpiprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_7480ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_knowled_efbf19_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_is_adde_da587a_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='added_by_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_added_by_kp_admin',
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/learners/'),
        ),
        migrations.AddField(
            model_name='kpinstructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kp_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='created_knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='users.kpprofile'),
        ),
        migrations.DeleteModel(
            name='KPAProfile',
        ),
        migrations.DeleteModel(
            name='KPIProfile',
        ),
    ]
