# Generated by Django 5.2.5 on 2025-09-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_training_partner'),
        ('users', '0006_kpinstructorprofile_kpprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgePartner',
        ),
    ]
