# Generated by Django 5.2.5 on 2025-09-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_knowledgepartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpinstructorprofile',
            name='availability_notes',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='current_institution',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Areas of interest (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, help_text='Knowledge Partner organization this learner belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='users.kpprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='kp_approval_status',
            field=models.CharField(choices=[('none', 'No Association'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text="Status of learner's association with Knowledge Partner", max_length=20),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='learning_goals',
            field=models.TextField(blank=True, help_text='What do you want to learn?', null=True),
        ),
    ]
