# Generated by Django 5.2.5 on 2025-09-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_kp_association_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpinstructorprofile',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, help_text='Knowledge Partner organization the instructor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='users.kpprofile'),
        ),
    ]
