# Generated by Django 5.2.5 on 2025-09-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_kpinstructorprofile_knowledge_partner'),
    ]

    operations = [
    ]
