# Generated by Django 5.2.5 on 2025-09-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_assign_kp_to_instructors'),
        ('users', '0011_alter_kpinstructorprofile_knowledge_partner'),
    ]

    operations = [
    ]
