# Generated by Django 5.2.5 on 2025-09-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('knowledge_partner_instructor', 'Instructor'), ('knowledge_partner', 'Knowledge Partner'), ('super_admin', 'Super Admin')], default='learner', max_length=30),
        ),
    ]
