# Generated by Django 5.2.5 on 2025-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpinstructorprofile',
            name='bio',
            field=models.TextField(help_text='Professional bio for learners to see'),
        ),
    ]
