# Generated by Django 5.2.5 on 2025-09-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_kpinstructorprofile_bio'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgepartnerapplication',
            name='users_knowl_knowled_06a0db_idx',
        ),
    ]
