# Generated by Django 5.2.5 on 2025-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_knowledgepartnerapplication_users_knowl_knowled_06a0db_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgepartnerapplication',
            index=models.Index(fields=['knowledge_partner_email'], name='users_kpapp_email_idx'),
        ),
    ]
