# Generated by Django 5.2.5 on 2025-09-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_knowledgepartnerapplication_users_kpapp_email_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgepartnerapplication',
            name='users_kpapp_email_idx',
        ),
    ]
