# Generated by Django 5.2.5 on 2025-09-21 07:21

from django.db import migrations


def fix_instructor_kp_references(apps, schema_editor):
    """
    Fix KPInstructorProfile records that have invalid knowledge_partner references.
    Assign them to the first available KPProfile or create a default one.
    """
    KPInstructorProfile = apps.get_model('users', 'KPInstructorProfile')
    KPProfile = apps.get_model('users', 'KPProfile')
    
    # Get all instructors with invalid knowledge_partner references
    invalid_instructors = KPInstructorProfile.objects.filter(knowledge_partner__isnull=True)
    
    if invalid_instructors.exists():
        # Get the first available KPProfile
        first_kp = KPProfile.objects.first()
        
        if first_kp:
            # Assign all invalid instructors to the first KP
            invalid_instructors.update(knowledge_partner=first_kp)
            print(f"Fixed {invalid_instructors.count()} instructor profiles by assigning them to KP: {first_kp.name}")
        else:
            # If no KP exists, create a default one
            default_kp = KPProfile.objects.create(
                name="Default Knowledge Partner",
                type="other",
                description="Default organization for orphaned instructors",
                location="Unknown",
                kp_admin_name="System Admin",
                kp_admin_email="admin@system.com"
            )
            invalid_instructors.update(knowledge_partner=default_kp)
            print(f"Created default KP and assigned {invalid_instructors.count()} instructor profiles to it")


def reverse_fix_instructor_kp_references(apps, schema_editor):
    """
    Reverse operation - set knowledge_partner to null for instructors
    """
    KPInstructorProfile = apps.get_model('users', 'KPInstructorProfile')
    KPInstructorProfile.objects.update(knowledge_partner=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_knowledgepartnerapplication_users_knowl_knowled_06a0db_idx'),
    ]

    operations = [
        migrations.RunPython(
            fix_instructor_kp_references,
            reverse_fix_instructor_kp_references,
        ),
    ]
