# Generated by Django 5.2.5 on 2025-09-21 07:21

from django.db import migrations


def fix_instructor_kp_references(apps, schema_editor):
    """
    Fix KPInstructorProfile records that have invalid knowledge_partner references.
    This handles both NULL values and references to non-existent KPProfile records.
    Ensures any created KPProfile has a valid user_id (NOT NULL).
    """
    from django.db import connection
    from django.contrib.auth.hashers import make_password

    # Use historical models from the migration state
    User = apps.get_model('users', 'User')
    KPProfile = apps.get_model('users', 'KPProfile')

    with connection.cursor() as cursor:
        # First, get all valid KP IDs using the historical KPProfile model
        valid_kp_ids = set(KPProfile.objects.values_list('id', flat=True))

        if not valid_kp_ids:
            # No KP exists, create a default KP *with* a valid user
            admin_email = 'admin@system.com'

            # Get or create a KP admin user for this default KP using the historical User model
            existing_user = User.objects.filter(email=admin_email).first()
            if existing_user:
                user = existing_user
                print(f"Using existing user for default KP: {admin_email}")
            else:
                # Create user using .create() since historical models don't have create_user
                user = User.objects.create(
                    email=admin_email,
                    password=make_password('ChangeMe123!'),
                    full_name='System Admin',
                    first_name='System',
                    last_name='Admin',
                    role='knowledge_partner',
                    is_verified=True,
                    is_approved=True,
                    is_active=True,
                    is_staff=False,
                    is_superuser=False,
                )
                print(f"Created new user for default KP: {admin_email}")

            # Create the default KPProfile using the historical KPProfile model
            kp_profile = KPProfile.objects.create(
                user=user,
                name='Default Knowledge Partner',
                type='other',
                description='Default organization for orphaned instructors',
                location='Unknown',
                website=None,
                kp_admin_name='System Admin',
                kp_admin_email=admin_email,
                kp_admin_phone=None,
                logo=None,
                linkedin_url=None,
                is_active=True,
                is_verified=False,
            )

            default_kp_id = kp_profile.id
            valid_kp_ids = {default_kp_id}
            print(f"Created default KP with ID: {default_kp_id}")
        else:
            # Use the first available KP
            default_kp_id = list(valid_kp_ids)[0]
            print(f"Using existing KP with ID: {default_kp_id}")

        # Find and fix all instructors with invalid knowledge_partner references
        cursor.execute(
            """
            SELECT id, knowledge_partner_id 
            FROM users_kpinstructorprofile 
            WHERE knowledge_partner_id IS NULL 
               OR knowledge_partner_id NOT IN %s
            """,
            [tuple(valid_kp_ids)],
        )

        invalid_instructors = cursor.fetchall()

        if invalid_instructors:
            print(
                f"Found {len(invalid_instructors)} instructor profiles with invalid "
                "knowledge_partner references"
            )

            # Update all invalid instructors to use the default KP
            instructor_ids = [str(instructor[0]) for instructor in invalid_instructors]
            
            # Use raw SQL for the update
            placeholders = ','.join(['%s'] * len(instructor_ids))
            cursor.execute(
                f"""
                UPDATE users_kpinstructorprofile 
                SET knowledge_partner_id = %s 
                WHERE id::text IN ({placeholders})
                """,
                [str(default_kp_id)] + instructor_ids,
            )

            print(f"Fixed {len(invalid_instructors)} instructor profiles")
        else:
            print("No invalid instructor profiles found")


def reverse_fix_instructor_kp_references(apps, schema_editor):
    """
    Reverse operation - can't really reverse this safely
    """
    print("Reverse migration: No action taken (data migration is not reversible)")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_knowledgepartnerapplication_users_knowl_knowled_06a0db_idx'),
    ]

    operations = [
        migrations.RunPython(
            fix_instructor_kp_references,
            reverse_fix_instructor_kp_references,
        ),
    ]