# Generated by Django 5.2.5 on 2025-09-21 09:57

from django.db import migrations


def fix_production_kp_references(apps, schema_editor):
    """
    Comprehensive fix for production foreign key constraint violations.
    This handles all possible scenarios including concurrent inserts.
    """
    from django.db import connection, transaction
    
    with connection.cursor() as cursor:
        with transaction.atomic():
            # Step 1: Temporarily disable the foreign key constraint
            cursor.execute("SET CONSTRAINTS users_kpinstructorpr_knowledge_partner_id_29832a33_fk_users_kpp DEFERRED")
            
            # Step 2: Get all valid KP IDs
            cursor.execute("SELECT id FROM users_kpprofile")
            valid_kp_ids = {row[0] for row in cursor.fetchall()}
            
            # Step 3: Create a default KP if none exists
            if not valid_kp_ids:
                cursor.execute("""
                    INSERT INTO users_kpprofile 
                    (id, name, type, description, location, kp_admin_name, kp_admin_email, 
                     is_active, is_verified, created_at, updated_at)
                    VALUES 
                    (gen_random_uuid(), 'Default Knowledge Partner', 'other', 
                     'Default organization for orphaned instructors', 'Unknown', 
                     'System Admin', 'admin@system.com', true, false, NOW(), NOW())
                """)
                
                # Get the newly created KP ID
                cursor.execute("SELECT id FROM users_kpprofile WHERE name = 'Default Knowledge Partner'")
                default_kp_id = cursor.fetchone()[0]
                print(f"Created default KP with ID: {default_kp_id}")
            else:
                # Use the first available KP
                default_kp_id = list(valid_kp_ids)[0]
                print(f"Using existing KP with ID: {default_kp_id}")
            
            # Step 4: Find all instructors with invalid knowledge_partner references
            cursor.execute("""
                SELECT id, knowledge_partner_id 
                FROM users_kpinstructorprofile 
                WHERE knowledge_partner_id IS NULL 
                   OR knowledge_partner_id NOT IN %s
            """, [tuple(valid_kp_ids)])
            
            invalid_instructors = cursor.fetchall()
            
            if invalid_instructors:
                print(f"Found {len(invalid_instructors)} instructor profiles with invalid knowledge_partner references")
                
                # Step 5: Update all invalid instructors to use the default KP
                instructor_ids = [instructor[0] for instructor in invalid_instructors]
                cursor.execute("""
                    UPDATE users_kpinstructorprofile 
                    SET knowledge_partner_id = %s 
                    WHERE id = ANY(%s)
                """, [default_kp_id, instructor_ids])
                
                print(f"Fixed {len(invalid_instructors)} instructor profiles")
            else:
                print("No invalid instructor profiles found")
            
            # Step 6: Re-enable the foreign key constraint
            cursor.execute("SET CONSTRAINTS users_kpinstructorpr_knowledge_partner_id_29832a33_fk_users_kpp IMMEDIATE")


def reverse_fix_production_kp_references(apps, schema_editor):
    """
    Reverse operation - this is not recommended as it will cause constraint violations
    """
    print("Reverse operation not supported for this migration")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_fix_instructor_kp_references'),
    ]

    operations = [
        migrations.RunPython(
            fix_production_kp_references,
            reverse_fix_production_kp_references,
        ),
    ]
