# Generated by Django 5.2.5 on 2025-09-28 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_fix_knowledge_partner_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address to send OTP to', max_length=254)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login_verification', 'Login Verification')], default='email_verification', max_length=30)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum verification attempts allowed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
