# Generated by Django 5.2.5 on 2025-09-28 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='temp_user_data',
            field=models.JSONField(blank=True, help_text='Temporary user data for pending registrations', null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User object (null for pending registrations)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
