# Generated by Django 5.2.5 on 2025-11-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_otpverification_temp_user_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='courses_interested_in',
            field=models.TextField(blank=True, help_text='Comma-separated list of areas of focus', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerapplication',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
