# Generated by Django 5.2.5 on 2026-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_add_apple_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from OAuth provider', max_length=500, null=True, verbose_name='Avatar URL'),
        ),
    ]
